service: back-end
runtime: nodejs12
entrypoint: npm start 
env_variables: 
    DB_URL: "mongodb+srv://lcrgnxEGMrC2auRO:lcrgnxEGMrC2auRO@cluster0.gnsur.gcp.mongodb.net/slowvid?retryWrites=true&w=majority"
