name: back-end
on:
  push:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
        working-directory: back-end
      - name: Build
        run: npm run build
        working-directory: back-end
      - name: Unit Test
        run: npm run test
        working-directory: back-end
